volumes:
  mariadb-data:

services:
  mariadb:
    image: mariadb:latest
    ports:
      - 3306:3306
    environment:
      - MARIADB_ROOT_PASSWORD=<your-root-password>
      - MARIADB_USER=<your-username>
      - MARIADB_PASSWORD=<your-password>
    volumes:
      - mariadb-data:/var/lib/mysql
    restart: unless-stopped