volumes:
  mariadb-data:

services:
  mariadb:
    image: mariadb:latest
    ports:
      - 3306:3306
    environment:
      - MARIADB_ROOT_USER=root
      - MARIADB_ROOT_PASSWORD=root
    volumes:
      - mariadb-data:/var/lib/mysql
    restart: unless-stopped