volumes:
  postgres-data:
    driver: local

services:
  postgres:
    container_name: postgres
    image: postgres:16.2-alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U "${POSTGRES_USER:-postgres}"']
      start_period: 30s
      interval: 10s
      timeout: 10s
      retries: 5
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_USER:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-$POSTGRES_USER}
      - TZ=${TZ:-UTC}
    volumes:
      - postgres-data:/var/lib/mysql
